# Generated by Django 4.2.15 on 2024-08-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_good', '0002_consumergood_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergood',
            name='general',
        ),
    ]
