# Generated by Django 4.2.15 on 2024-09-05 16:47

from django.db import migrations, models
import ecolens.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_distance', models.FloatField(default=0, help_text='e.g., 1000', validators=[ecolens.custom_validators.validate_min])),
                ('flight_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[ecolens.custom_validators.validate_distance_unit])),
                ('public_transit_distance', models.FloatField(default=0, help_text='e.g., 1000', validators=[ecolens.custom_validators.validate_min])),
                ('transit_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[ecolens.custom_validators.validate_distance_unit])),
                ('company_num_of_gasolin_cars', models.IntegerField(default=0, help_text='e.g., 1')),
                ('company_num_of_diesel_cars', models.IntegerField(default=0, help_text='e.g., 1')),
                ('company_num_of_electric_cars', models.IntegerField(default=0, help_text='e.g., 1')),
                ('company_num_of_hybrid_cars', models.IntegerField(default=0, help_text='e.g., 1')),
                ('company_gasoline_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('company_diesel_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('company_electric_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('company_hybrid_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('staff_gasoline_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('staff_diesel_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('staff_electric_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('staff_hybrid_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('gasolin_car_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[ecolens.custom_validators.validate_distance_unit])),
                ('diesel_car_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[ecolens.custom_validators.validate_distance_unit])),
                ('electric_car_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[ecolens.custom_validators.validate_distance_unit])),
                ('hybrid_car_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[ecolens.custom_validators.validate_distance_unit])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_emission', models.FloatField(default=0)),
                ('public_transit_emission', models.FloatField(default=0)),
                ('company_gasoline_car_emissions', models.FloatField(default=0)),
                ('company_diesel_car_emissions', models.FloatField(default=0)),
                ('company_electric_car_emissions', models.FloatField(default=0)),
                ('company_hybrid_car_emissions', models.FloatField(default=0)),
                ('staff_gasoline_car_emissions', models.FloatField(default=0)),
                ('staff_diesel_car_emissions', models.FloatField(default=0)),
                ('staff_electric_car_emissions', models.FloatField(default=0)),
                ('staff_hybrid_car_emissions', models.FloatField(default=0)),
                ('vehicle_footprint', models.FloatField(default=0)),
                ('emission_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/USD', 'equivalent carbon units per dollar')], default='tCO2equ', max_length=12)),
            ],
        ),
    ]
