# Generated by Django 4.2.15 on 2024-08-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint', '0002_emission_business_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='total_emission',
            field=models.FloatField(default=0),
        ),
    ]
