# import Libraries
import enum
from .helper import CONF


class DistanceUnit(enum.Enum):
    Km = "Km"
    Mi = "Mi"


# BUSINESS_TRAVEL
BUSINESS_FLIGHT_DISTANCE_CONVERSION_FACTORS = {
    DistanceUnit.Km.value: CONF["BUSINESS_FLIGHT_EMISSIONS_PER_KM"],
    # Add conversion factors for other units
}

BUSINESS_PUBLIC_TRNSIT_CONVERSION_FACTORS = {
    DistanceUnit.Km.value: CONF["BUSINESS_TRANSIT_EMISSIONS_PER_KM"],
}
# CAR_EMISSION_COMPANY_VEHICLES
BUSINESS_GASOLINE_CAR_MANUFACTURING_EMISSIONS = {
    DistanceUnit.Km.value: CONF["BUSINESS_GASOLINE_CAR_MANUFACTURING_EMISSIONS"],
}

BUSINESS_DIESEL_CAR_MANUFACTURING_EMISSIONS = {
    DistanceUnit.Km.value: CONF["BUSINESS_DIESEL_CAR_MANUFACTURING_EMISSIONS"],
}

BUSINESS_ELECTRIC_CAR_MANUFACTURING_EMISSIONS = {
    DistanceUnit.Km.value: CONF["BUSINESS_ELECTRIC_CAR_MANUFACTURING_EMISSIONS"],
}

BUSINESS_HYBRID_CAR_MANUFACTURING_EMISSIONS = {
    DistanceUnit.Km.value: CONF["BUSINESS_HYBRID_CAR_MANUFACTURING_EMISSIONS"],
}

BUSINESS_GASOLINE_CAR_EMISSIONS_PER_KM = {
    DistanceUnit.Km.value: CONF["BUSINESS_GASOLINE_CAR_EMISSIONS_PER_KM"],
}

BUSINESS_DISEL_CAR_EMISSIONS_PER_KM = {
    DistanceUnit.Km.value: CONF["BUSINESS_DISEL_CAR_EMISSIONS_PER_KM"],
}

BUSINESS_ELECTRIC_CAR_EMISSIONS_PER_KM = {
    DistanceUnit.Km.value: CONF["BUSINESS_ELECTRIC_CAR_EMISSIONS_PER_KM"],
}
BUSINESS_HYBRID_CAR_EMISSIONS_PER_KM = {
    DistanceUnit.Km.value: CONF["BUSINESS_HYBRID_CAR_EMISSIONS_PER_KM"],
}

# CAR_EMISSION_STAFF_COMMUTE
STAFF_GASOLINE_CAR_EMISSIONS_PER_KM = {
    DistanceUnit.Km.value: CONF["STAFF_GASOLINE_CAR_EMISSIONS_PER_KM"],
}

STAFF_DISEL_CAR_EMISSIONS_PER_KM = {
    DistanceUnit.Km.value: CONF["STAFF_DISEL_CAR_EMISSIONS_PER_KM"],
}

STAFF_ELECTRIC_CAR_EMISSIONS_PER_KM = {
    DistanceUnit.Km.value: CONF["STAFF_ELECTRIC_CAR_EMISSIONS_PER_KM"],
}
STAFF_HYBRID_CAR_EMISSIONS_PER_KM = {
    DistanceUnit.Km.value: CONF["STAFF_HYBRID_CAR_EMISSIONS_PER_KM"],
}
