# Generated by Django 4.2.15 on 2024-09-05 16:47

from django.db import migrations, models
import django.db.models.deletion
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diet_type', models.CharField(choices=[('VI', 'Vegan'), ('VG', 'Vegetarian'), ('FL', 'Flexitarian'), ('PE', 'PESCETARIAN'), ('OM', 'Omnivore'), ('CA', 'CARNIVORE'), ('KE', 'KETO'), ('PA', 'PALEO')], default='VI', max_length=2)),
                ('consumption_level', models.CharField(choices=[('Minimal', 'Minimal consumption'), ('Low', 'Low consumption'), ('Moderate', 'Moderate consumption'), ('High', 'High Consumption')], default='Low', help_text='Select the appropriate waste category based on the percentage.', max_length=8)),
                ('level_of_wastage', models.FloatField(default=0.0, help_text='e.g. 0.3 to represent 30%', validators=[food.models.validate_wastage_label])),
                ('consumption_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ/year', max_length=12)),
                ('diet_emission', models.FloatField(default=0)),
                ('diet_emission_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('wastage_emission', models.FloatField(default=0)),
                ('wastage_emission_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('food_footprint', models.FloatField(default=0)),
                ('food_footprint_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.general')),
            ],
        ),
    ]
