# Generated by Django 4.2.15 on 2024-08-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_initial'),
        ('vehicle_usages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diet_type', models.CharField(choices=[('VI', 'Vegan'), ('VG', 'Vegetarian'), ('FL', 'Flexitarian'), ('OM', 'Omnivore')], default='VI', max_length=3)),
                ('consumption_level', models.FloatField(default=0.0, help_text='e.g. 0.3 to represent 30%')),
                ('Vehicle_usages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_usages.vehicleusages')),
                ('household_usages', models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='household.householdusages')),
            ],
        ),
    ]
