# Generated by Django 4.2.15 on 2024-08-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_foodconsumption_household_usages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodconsumption',
            name='Vehicle_usages',
        ),
        migrations.RemoveField(
            model_name='foodconsumption',
            name='household_usages',
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='diet_type',
            field=models.CharField(choices=[('VI', 'Vegan'), ('VG', 'Vegetarian'), ('FL', 'Flexitarian'), ('OM', 'Omnivore')], default='VI', max_length=2),
        ),
    ]
