# Generated by Django 4.2.15 on 2024-08-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_foodconsumption_vehicle_usages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumption',
            name='level_of_wastage',
            field=models.CharField(choices=[('0%', 'Minimal Waste'), ('0 to 10%', 'Low Waste'), ('10 to 25%', 'Moderate Waste'), ('> 25%', 'High Waste')], default='0 to 10%', help_text='Select the appropriate waste category based on the percentage.', max_length=10),
        ),
    ]
