# Generated by Django 4.2.15 on 2024-08-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodconsumption_level_of_wastage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodconsumption',
            name='level_of_wastage',
            field=models.CharField(choices=[('0%', 'Minimal Waste'), ('0 to 10%', 'Low Waste'), ('10 to 25%', 'Moderate Waste'), ('> 25%', 'High Waste')], default='0 to 10%', help_text='Select the appropriate waste category based on the percentage.\n         0%: Minimal Waste, 0 to 10%: Low Waste, 10 to 25%:Moderate Waste, >255%: High Waste', max_length=10),
        ),
    ]
