# Generated by Django 4.2.15 on 2024-08-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_foodconsumption_level_of_wastage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodconsumption',
            name='consumption_level',
        ),
        migrations.RemoveField(
            model_name='foodconsumption',
            name='level_of_wastage',
        ),
    ]
