# Generated by Django 4.2.15 on 2024-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_foodconsumption_consumption_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumption',
            name='consumption_level',
            field=models.CharField(choices=[('Minimul', 'Minimal consumption'), ('Low', 'Low consumption'), ('Moderate', 'Moderate consumption'), ('High', 'High Consumption')], default='Low', help_text='Select the appropriate waste category based on the percentage.\n         0%: Minimal Waste, 0 to 10%: Low Waste, 10 to 25%:Moderate Waste, >255%: High Waste', max_length=8),
        ),
    ]
