# Generated by Django 4.2.15 on 2024-08-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_foodconsumption_level_of_wastage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumption',
            name='diet_emission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='diet_emission_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant')], default='tCO2equ', max_length=10),
        ),
    ]
