# Generated by Django 4.2.15 on 2024-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_foodconsumption_diet_emission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumption',
            name='wastage_emission',
            field=models.FloatField(default=0),
        ),
    ]
