# Generated by Django 4.2.15 on 2024-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_foodconsumption_wastage_emission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodconsumption',
            name='consumption_level',
            field=models.CharField(choices=[('Minimul', 'Minimal consumption'), ('Low', 'Low consumption'), ('Moderate', 'Moderate consumption'), ('', 'High Consumption')], default='Low', help_text='Select the appropriate waste category based on the percentage.\n         0%: Minimal Waste, 0 to 10%: Low Waste, 10 to 25%:Moderate Waste, >255%: High Waste', max_length=8),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='level_of_wastage',
            field=models.CharField(choices=[('Minimul', '0%'), ('Low', '0 to 10%'), ('Moderate', '10 to 25%'), ('High', '> 25%')], default='Low', help_text='Select the appropriate waste category based on the percentage.\n         0%: Minimal Waste, 0 to 10%: Low Waste, 10 to 25%:Moderate Waste, >255%: High Waste', max_length=10),
        ),
    ]
