# Generated by Django 4.2.15 on 2024-08-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_foodconsumption_consumption_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodconsumption',
            name='level_of_wastage',
        ),
    ]
