# Generated by Django 4.2.15 on 2024-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_remove_foodconsumption_level_of_wastage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodconsumption',
            name='diet_type',
            field=models.CharField(choices=[('VI', 'Vegan'), ('VG', 'Vegetarian'), ('FL', 'Flexitarian'), ('PE', 'PESCETARIAN'), ('OM', 'Omnivore'), ('CA', 'CARNIVORE'), ('KE', 'KETO'), ('PA', 'PALEO')], default='VI', max_length=2),
        ),
    ]
