# Generated by Django 4.2.15 on 2024-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_alter_foodconsumption_diet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumption',
            name='level_of_wastage',
            field=models.CharField(choices=[('0%', 'Minimal'), ('0 to 10%', 'Low'), ('10 to 25%', 'Moderate'), ('> 25%', 'High')], default='0 to 10%', help_text='Select the appropriate waste category based on the percentage.\n         0%: Minimal Waste, 0 to 10%: Low Waste, 10 to 25%:Moderate Waste, >255%: High Waste', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='consumption_level',
            field=models.CharField(choices=[('Minimal', 'Minimal consumption'), ('Low', 'Low consumption'), ('Moderate', 'Moderate consumption'), ('High', 'High Consumption')], default='Low', help_text='Select the appropriate waste category based on the percentage.\n         0%: Minimal Waste, 0 to 10%: Low Waste, 10 to 25%:Moderate Waste, >255%: High Waste', max_length=8),
        ),
    ]
