# Generated by Django 4.2.15 on 2024-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_foodconsumption_food_footprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumption',
            name='consumption_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ/year', max_length=12),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='diet_emission_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='food_footprint_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='wastage_emission_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
    ]
