# Generated by Django 4.2.15 on 2024-08-20 15:32

from django.db import migrations, models
import ecolens.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUsages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('education', models.FloatField(default=0, help_text='Amount in USD,e.g.,500', validators=[ecolens.custom_validators.validate_min])),
                ('activities', models.FloatField(default=0, help_text='Amount in USD,e.g.,1000', validators=[ecolens.custom_validators.validate_min])),
                ('consumption_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/USD', 'equivalent carbon units per dollar')], default='tCO2equ/USD', max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_emission', models.FloatField(default=0)),
                ('activities_emission', models.FloatField(default=0)),
                ('public_services_emission', models.FloatField(default=0)),
                ('other_emission', models.FloatField(default=0)),
                ('emission_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/USD', 'equivalent carbon units per dollar')], default='tCO2equ', max_length=13)),
            ],
        ),
    ]
