# Generated by Django 4.2.14 on 2024-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleUsages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_distance', models.FloatField(default=0)),
                ('flight_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], max_length=2)),
            ],
        ),
    ]
