# Generated by Django 4.2.15 on 2024-09-02 06:39

from django.db import migrations, models
import vehicle_usages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleUsages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_distance', models.FloatField(default=0, help_text='e.g., 1000', validators=[vehicle_usages.models.validate_min_distance])),
                ('flight_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit])),
                ('public_transit_distance', models.FloatField(default=0, help_text='e.g., 1000', validators=[vehicle_usages.models.validate_min_distance])),
                ('transit_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit])),
                ('num_of_gasolin_cars', models.IntegerField(default=0, help_text='e.g., 1')),
                ('num_of_diesel_cars', models.IntegerField(default=0, help_text='e.g., 1')),
                ('num_of_electric_cars', models.IntegerField(default=0, help_text='e.g., 1')),
                ('num_of_hybrid_cars', models.IntegerField(default=0, help_text='e.g., 1')),
                ('gasoline_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('gasolin_car_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit])),
                ('diesel_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('diesel_car_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit])),
                ('electric_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('electric_car_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit])),
                ('hybrid_car_driven', models.FloatField(default=0, help_text='e.g., 100')),
                ('hybrid_car_unit', models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit])),
                ('flight_emission', models.FloatField(default=0)),
                ('flight_emission_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('public_transit_emission', models.FloatField(default=0)),
                ('transit_emission_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('gasoline_car_emissions', models.FloatField(default=0)),
                ('gasoline_car_emission_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('diesel_car_emissions', models.FloatField(default=0)),
                ('diesel_car_emissions_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('electric_car_emissions', models.FloatField(default=0)),
                ('electric_car_emissions_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('hybrid_car_emissions', models.FloatField(default=0)),
                ('hybrid_car_emissions_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('vehicle_footprint', models.FloatField(default=0)),
                ('vehicle_footprint_unit', models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
