# Generated by Django 4.2.15 on 2024-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_usages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleusages',
            name='vehicle_emissions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='vehicle_emissions_unit',
            field=models.CharField(choices=[('tCO2', 'Tons of Carbon Dioxide')], default='tCO2', max_length=10),
        ),
    ]
