# Generated by Django 4.2.14 on 2024-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_usages', '0002_vehicleusages_public_transit_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleusages',
            name='diesel_car_driven',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='diesel_car_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='electric_car_driven',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='electric_car_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='gasoline_car_driven',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='hybrid_car_driven',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='hybrid_car_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='num_of_diesel_cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='num_of_electric_cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='num_of_gasolin_cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='num_of_hybrid_cars',
            field=models.IntegerField(default=0),
        ),
    ]
