# Generated by Django 4.2.14 on 2024-08-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_usages', '0003_vehicleusages_diesel_car_driven_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleusages',
            name='flight_emission',
            field=models.FloatField(default=0),
        ),
    ]
