# Generated by Django 4.2.15 on 2024-08-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_usages', '0003_rename_vehicle_emissions_vehicleusages_vehicle_footprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleusages',
            name='diesel_car_emissions_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='electric_car_emissions_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='flight_emission_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='gasoline_car_emission_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='hybrid_car_emissions_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='transit_emission_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='vehicle_footprint_unit',
            field=models.CharField(choices=[('tCO2equ', 'Tons of Carbon Dioxide Equvalant'), ('tCO2equ/year', 'Tons of Carbon Dioxide Equvalant per year')], default='tCO2equ', max_length=12),
        ),
    ]
