# Generated by Django 4.2.14 on 2024-08-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_usages', '0004_vehicleusages_flight_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleusages',
            name='gasolin_car_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='gasoline_car_emissions',
            field=models.FloatField(default=0),
        ),
    ]
