# Generated by Django 4.2.14 on 2024-08-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_usages', '0005_vehicleusages_gasolin_car_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleusages',
            name='diesel_car_emissions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='diesel_car_emissions_unit',
            field=models.CharField(blank=True, choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='electric_car_emissions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='electric_car_emissions_unit',
            field=models.CharField(blank=True, choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='flight_emission_unit',
            field=models.CharField(blank=True, choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='gasoline_car_emission_unit',
            field=models.CharField(blank=True, choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='hybrid_car_emissions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='hybrid_car_emissions_unit',
            field=models.CharField(blank=True, choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='public_transit_emission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='transit_emission_unit',
            field=models.CharField(blank=True, choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='electric_car_unit',
            field=models.CharField(blank=True, choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='flight_unit',
            field=models.CharField(blank=True, choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='gasolin_car_unit',
            field=models.CharField(blank=True, choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='hybrid_car_unit',
            field=models.CharField(blank=True, choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='transit_unit',
            field=models.CharField(blank=True, choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2),
        ),
    ]
