# Generated by Django 4.2.14 on 2024-08-08 15:10

from django.db import migrations, models
import django.utils.timezone
import vehicle_usages.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_usages', '0006_vehicleusages_diesel_car_emissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleusages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleusages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='diesel_car_driven',
            field=models.FloatField(default=0, help_text='e.g., 100'),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='diesel_car_emissions_unit',
            field=models.CharField(choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='diesel_car_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit]),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='electric_car_driven',
            field=models.FloatField(default=0, help_text='e.g., 100'),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='electric_car_emissions_unit',
            field=models.CharField(choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='electric_car_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit]),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='flight_distance',
            field=models.FloatField(default=0, help_text='e.g., 1000', validators=[vehicle_usages.models.validate_min_distance]),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='flight_emission_unit',
            field=models.CharField(choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='flight_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit]),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='gasolin_car_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit]),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='gasoline_car_driven',
            field=models.FloatField(default=0, help_text='e.g., 100'),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='gasoline_car_emission_unit',
            field=models.CharField(choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='hybrid_car_driven',
            field=models.FloatField(default=0, help_text='e.g., 100'),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='hybrid_car_emissions_unit',
            field=models.CharField(choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='hybrid_car_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit]),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='num_of_diesel_cars',
            field=models.IntegerField(default=0, help_text='e.g., 1'),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='num_of_electric_cars',
            field=models.IntegerField(default=0, help_text='e.g., 1'),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='num_of_gasolin_cars',
            field=models.IntegerField(default=0, help_text='e.g., 1'),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='num_of_hybrid_cars',
            field=models.IntegerField(default=0, help_text='e.g., 1'),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='public_transit_distance',
            field=models.FloatField(default=0, help_text='e.g., 1000', validators=[vehicle_usages.models.validate_min_distance]),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='transit_emission_unit',
            field=models.CharField(choices=[('tCO2eq', 'Tons of Carbon Dioxide Equivalent'), ('tCO2eq/km', 'Tons of Carbon Dioxide Equivalent per Kilometer')], default='tCO2eq/km', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleusages',
            name='transit_unit',
            field=models.CharField(choices=[('Km', 'Kilometer'), ('Mi', 'Mile')], default='Km', max_length=2, validators=[vehicle_usages.models.validate_distance_unit]),
        ),
    ]
